module.exports = {
    eval: require("../eval"),
    join: require("./join"),
    part: require("./part"),
    say: require("../say"),
    test: require("../test"),
    // test2: require("./test2"),
    clip: require("../createclip"),
    user: require("../user"),
    timer: require("../timer"),
    tuck: require("../tuck"),
    rank: require("../valorantrank"),
    rank2: require("../valorantrank2"),
    
    botinfo: require("../botinfo"),
    serverinfo: require("../server"),
    setting: require("../settings"),
    settings: require("../settings"),
    "7tv": require("../seventv"),
    seventv: require("../seventv"),
    download: require("../download"),
    view: require("../view"),
    unview: require("../unview"),
    afk: require("./afk"),
    gn: require("./afk"),
    cafk: require("./afk"),
    rafk: require("./afk"),
    ping: require("../botinfo"),
    
    command: require("./customcommand"),
    commands: require("./customcommand"),
    addcmd: require("./customcommand"),
    delcmd: require("./customcommand"),
    editcmd: require("./customcommand"),
    renamecmd: require("./customcommand"),
    permcmd: require("./customcommand"),
    enablecmd: require("./customcommand"),
    disablecmd: require("./customcommand"),
    getcmd: require("./customcommand"),
    infocmd: require("./customcommand"),
    listcmd: require("./customcommand"),
    copycmd: require("./customcommand"),
    yoinkcmd: require("./customcommand"),
    cooldowncmd: require("./customcommand"),

    keyword: require("./customkeyword"),
    keywords: require("./customkeyword"),
    addkey: require("./customkeyword"),
    delkey: require("./customkeyword"),
    editkey: require("./customkeyword"),
    renamekey: require("./customkeyword"),
    permkey: require("./customkeyword"),
    enablekey: require("./customkeyword"),
    disablekey: require("./customkeyword"),
    getkey: require("./customkeyword"),
    infokey: require("./customkeyword"),
    listkey: require("./customkeyword"),
    copykey: require("./customkeyword"),
    yoinkkey: require("./customkeyword"),
    cooldownkey: require("./customkeyword"),

    notification: require("./customnotification"),
    notifications: require("./customnotification"),
    addnotification: require("./customnotification"),
    deletenotification: require("./customnotification"),
    removenotification: require("./customnotification"),
    editnotification: require("./customnotification"),
    enablenotification: require("./customnotification"),
    disablenotification: require("./customnotification"),
    
    permission: require("../permission"),
    getperm: require("../permission"),

    remind: require("../reminder"),
    reminder: require("../reminder"),
    remindme: require("../reminder"),

    phrase: require("../phrase"),
    randomphrase: require("../phrase"),

    logchannel: require("./logchannel"),
    logchannels: require("./logchannel"),
    todo: require("../todo"),
    
    restart: require("../poweroptions"),

    tracker: require("./customtracker"),
    activemods: require("../trackers/activemods"),

    cache: require("../cache"),

    knownbots: require("../knownbots"),
    addknownbot: require("../knownbots"),
    removeknownbot: require("../knownbots"),
    deleteknownbot: require("../knownbots"),
    getknownbot: require("../knownbots"),
    getknownbots: require("../knownbots"),

    clipinfo: require("../getclip"),
    videoinfo: require("../getvideo"),
    streaminfo: require("../getstream"),

    // poll: require("./createpoll"),

    errors: require("../api/geterrors"),

    question: require("../openai_question"),
    flush: require("../flush"),

    school: require("./school_days_left"),

    pcon: require("../pcpower"),
    pcoff: require("../pcpower"),

};