module.exports = {
    eval: require("./eval"),
    join: require("./join"),
    part: require("./part"),
    say: require("./say"),
    test: require("./test"),
    // test2: require("./test2"),
    clip: require("./clip"),
    user: require("./user"),
    timer: require("./timer"),
    tuck: require("./tuck"),
    rank: require("./_valorantrank"),
    rank2: require("./_valorantrank2"),
    
    botinfo: require("./botinfo"),
    serverinfo: require("./server"),
    setting: require("./settings"),
    settings: require("./settings"),
    "7tv": require("./seventv"),
    seventv: require("./seventv"),
    download: require("./download"),
    view: require("./view"),
    unview: require("./unview"),
    afk: require("./afk"),
    gn: require("./afk"),
    cafk: require("./afk"),
    rafk: require("./afk"),
    ping: require("./botinfo"),
    
    command: require("./customcommand"),
    commands: require("./customcommand"),
    addcmd: require("./customcommand"),
    delcmd: require("./customcommand"),
    editcmd: require("./customcommand"),
    renamecmd: require("./customcommand"),
    permcmd: require("./customcommand"),
    enablecmd: require("./customcommand"),
    disablecmd: require("./customcommand"),
    getcmd: require("./customcommand"),

    keyword: require("./customkeyword"),
    keywords: require("./customkeyword"),
    addkey: require("./customkeyword"),
    delkey: require("./customkeyword"),
    editkey: require("./customkeyword"),
    renamekey: require("./customkeyword"),
    permkey: require("./customkeyword"),
    enablekey: require("./customkeyword"),
    disablekey: require("./customkeyword"),
    getkey: require("./customkeyword"),

    notification: require("./customnotification"),
    addnotification: require("./customnotification"),
    deletenotification: require("./customnotification"),
    removenotification: require("./customnotification"),
    editnotification: require("./customnotification"),
    enablenotification: require("./customnotification"),
    disablenotification: require("./customnotification"),
    
    permission: require("./permission"),

    remind: require("./reminder"),
    remindme: require("./reminder"),

}