module.exports = {
    oauth: require("../oauth"),
    eval: require("../eval"),
    join: require("../twitch/join"),
    part: require("../twitch/part"),
    say: require("../say"),
    test: require("../test"),
    // test2: require("../test2"),
    clip: require("../createclip"),
    user: require("../user"),
    timer: require("../timer"),
    tuck: require("../tuck"),
    rank: require("../valorantrank"),
    rank2: require("../valorantrank2"),
    
    botinfo: require("../botinfo"),
    serverinfo: require("../server"),
    setting: require("../settings"),
    settings: require("../settings"),
    "7tv": require("../seventv"),
    seventv: require("../seventv"),
    download: require("../download"),
    view: require("../view"),
    unview: require("../unview"),
    afk: require("../twitch/afk"),
    gn: require("../twitch/afk"),
    cafk: require("../twitch/afk"),
    rafk: require("../twitch/afk"),
    ping: require("../botinfo"),
    
    command: require("../twitch/customcommand"),
    commands: require("../twitch/customcommand"),
    addcmd: require("../twitch/customcommand"),
    delcmd: require("../twitch/customcommand"),
    editcmd: require("../twitch/customcommand"),
    renamecmd: require("../twitch/customcommand"),
    permcmd: require("../twitch/customcommand"),
    enablecmd: require("../twitch/customcommand"),
    disablecmd: require("../twitch/customcommand"),
    getcmd: require("../twitch/customcommand"),

    keyword: require("../twitch/customkeyword"),
    keywords: require("../twitch/customkeyword"),
    addkey: require("../twitch/customkeyword"),
    delkey: require("../twitch/customkeyword"),
    editkey: require("../twitch/customkeyword"),
    renamekey: require("../twitch/customkeyword"),
    permkey: require("../twitch/customkeyword"),
    enablekey: require("../twitch/customkeyword"),
    disablekey: require("../twitch/customkeyword"),
    getkey: require("../twitch/customkeyword"),

    notification: require("../twitch/customnotification"),
    notifications: require("../twitch/customnotification"),
    addnotification: require("../twitch/customnotification"),
    deletenotification: require("../twitch/customnotification"),
    removenotification: require("../twitch/customnotification"),
    editnotification: require("../twitch/customnotification"),
    enablenotification: require("../twitch/customnotification"),
    disablenotification: require("../twitch/customnotification"),
    
    permission: require("../permission"),

    remind: require("../reminder"),
    reminder: require("../reminder"),
    remindme: require("../reminder"),

    phrase: require("../phrase"),
    randomphrase: require("../phrase"),

    logchannel: require("../twitch/logchannel"),
    logchannels: require("../twitch/logchannel"),
    todo: require("../todo"),
    
    restart: require("../poweroptions"),

    tracker: require("../twitch/customtracker"),
    activemods: require("../trackers/activemods"),

    cache: require("../cache"),

    knownbots: require("../knownbots"),
    addknownbot: require("../knownbots"),
    removeknownbot: require("../knownbots"),
    deleteknownbot: require("../knownbots"),
    getknownbot: require("../knownbots"),
    getknownbots: require("../knownbots"),

    // crossban: require("../crossban"),

    clipinfo: require("../getclip"),
}